<?php
/**
 * @file
 * cadastro.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function cadastro_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_cadastro_nome'.
  $field_bases['field_cadastro_nome'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_cadastro_nome',
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(
      'max_length' => 255,
    ),
    'translatable' => 0,
    'type' => 'text',
  );

  // Exported field_base: 'field_cadastro_sobrenome'.
  $field_bases['field_cadastro_sobrenome'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_cadastro_sobrenome',
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(
      'max_length' => 255,
    ),
    'translatable' => 0,
    'type' => 'text',
  );

  return $field_bases;
}
